/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
*Hecho por Alexis Robles
*31/11/2022
*Formulario para Logear al sistema
 */
package Forms;
import Clases.cUsuarioCrud;
import Clases.conexion;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelFondo1 = new javax.swing.JLabel();
        PanelFondo2 = new javax.swing.JPanel();
        LabelLogin = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonIngresar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Label3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jpwClave = new javax.swing.JPasswordField();
        jtextUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\LogoPrincipalColegio.png")); // NOI18N
        PanelFondo1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 260, 260));

        LabelFondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\FondoLogin.png")); // NOI18N
        PanelFondo1.add(LabelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 550));

        PanelFondo2.setBackground(new java.awt.Color(255, 255, 255));
        PanelFondo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelFondo2.add(LabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, -1));

        Label1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("INICIAR SESIÓN");
        PanelFondo2.add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 430, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        PanelFondo2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 330, 10));

        botonIngresar.setText("INGRESAR");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        PanelFondo2.add(botonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 130, 57));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        PanelFondo2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 343, 330, 10));

        Label3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Label3.setForeground(new java.awt.Color(153, 153, 153));
        Label3.setText("Correo o Código de Administrador");
        PanelFondo2.add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 330, 36));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        PanelFondo2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 343, 330, 10));

        jpwClave.setBorder(null);
        PanelFondo2.add(jpwClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 330, 40));
        PanelFondo2.add(jtextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 330, -1));

        PanelFondo1.add(PanelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 430, 550));

        getContentPane().add(PanelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 692, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
         String Usuario =jtextUsuario.getText();
        String Clave =String.valueOf(jpwClave.getPassword()) ;
       conexion con= new conexion();
       Connection conectar=con.establecerConexion();
       cUsuarioCrud val= new cUsuarioCrud();
       int VALOR=val.ValidarLoginUsuario(conectar, Usuario, Clave);
       
       if (VALOR==0){
            JOptionPane.showMessageDialog(null,"Usuario o clave erronea intentelo nuevamente"); 
        }
       else if (VALOR==1){
        //JOptionPane.showMessageDialog(null,"Ok Usuario Encontrado"); 
        Principal menu =new Principal();
        menu.usuariologin(Usuario);
       // FrmMenu menu =new FrmMenu();
        menu.setVisible(true);
        }
        else if (VALOR==2){
        //JOptionPane.showMessageDialog(null,"Ok Usuario Encontrado"); 
        PrincipalDocente menu =new PrincipalDocente();
        menu.usuariologin(Usuario);
       // FrmMenu menu =new FrmMenu();
        menu.setVisible(true);
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel LabelFondo1;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JPanel PanelFondo1;
    private javax.swing.JPanel PanelFondo2;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField jpwClave;
    private javax.swing.JTextField jtextUsuario;
    // End of variables declaration//GEN-END:variables
}
