/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
*Hecho por Alexis Robles
*31/11/2022
*Formulario para Logear al sistema
 */
package Forms;

import Clases.Horario;
import Clases.cHorarioCrud;
import Clases.conexion;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class NuevoHorario extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    int IdPersonal=0;
    String IdHorario;
    public NuevoHorario() {
        initComponents();
         this.setLocationRelativeTo(null);
    }
 conexion con= new conexion();
 Connection conectar=con.establecerConexion(); 
 
   void ListarDataHorario(String IdHorario2,String Codigo,String HoraInicio,String HoraFin,String HorasSem,String Curso,String CantDiaLab,String Dias){
        jtextCodigoDocente.setText(Codigo);
       jtextHoraInicio.setText(HoraInicio);
       jtextHoraFin.setText(HoraFin);
       jtextCantHora.setText(HorasSem);
       jtextCurso.setText(Curso);
       jtextCantDiaLab.setText(CantDiaLab);
       IdHorario=IdHorario2;
       jbGuardarHorario.setText("Editar");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBlanco = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        PanelNuevoHorario = new javax.swing.JPanel();
        PanelLetrero = new javax.swing.JPanel();
        Letrero1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextCodigoDocente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtextHoraFin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtextCurso = new javax.swing.JTextField();
        jtextCantDiaLab = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jchkVie = new javax.swing.JCheckBox();
        jchkMie = new javax.swing.JCheckBox();
        jchkLun = new javax.swing.JCheckBox();
        jchkTodos = new javax.swing.JCheckBox();
        jchkJue = new javax.swing.JCheckBox();
        jchkMar = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jtextHoraInicio = new javax.swing.JTextField();
        jtextCantHora = new javax.swing.JTextField();
        jbLimpiar = new javax.swing.JButton();
        jbGuardarHorario = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        PanelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("CERRAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelBlanco.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 150, 30));

        getContentPane().add(PanelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 30));

        PanelNuevoHorario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLetrero.setBackground(new java.awt.Color(0, 2, 17));

        Letrero1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero1.setForeground(new java.awt.Color(255, 255, 255));
        Letrero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero1.setText("NUEVO HORARIO");

        javax.swing.GroupLayout PanelLetreroLayout = new javax.swing.GroupLayout(PanelLetrero);
        PanelLetrero.setLayout(PanelLetreroLayout);
        PanelLetreroLayout.setHorizontalGroup(
            PanelLetreroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Letrero1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        PanelLetreroLayout.setVerticalGroup(
            PanelLetreroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLetreroLayout.createSequentialGroup()
                .addComponent(Letrero1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelNuevoHorario.add(PanelLetrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 80));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo Docente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 20));

        jLabel2.setText("Curso");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 20));

        jLabel3.setText("Hora Inicio de Jornada");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 20));
        jPanel1.add(jtextCodigoDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, -1));

        jLabel4.setText("Hora Final de Jornada");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 20));
        jPanel1.add(jtextHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, -1));

        jLabel5.setText("Cantidad de Horas Semanales");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, 20));
        jPanel1.add(jtextCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 190, -1));
        jPanel1.add(jtextCantDiaLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, -1));

        jLabel6.setText("Cantidad de Días Laborales");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 160, 20));

        jLabel7.setText("Días");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 37, 20));

        jchkVie.setText("Viernes");
        jPanel1.add(jchkVie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 85, -1));

        jchkMie.setText("Miercoles");
        jPanel1.add(jchkMie, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 85, -1));

        jchkLun.setText("Lunes");
        jPanel1.add(jchkLun, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 85, -1));

        jchkTodos.setText("Todos");
        jPanel1.add(jchkTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 85, -1));

        jchkJue.setText("Jueves");
        jPanel1.add(jchkJue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 85, -1));

        jchkMar.setText("Martes");
        jPanel1.add(jchkMar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 85, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\LogoPrincipalColegio.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 270, 250));
        jPanel1.add(jtextHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 190, -1));
        jPanel1.add(jtextCantHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 190, -1));

        PanelNuevoHorario.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 740, 410));

        jbLimpiar.setText("LIMPIAR TODO");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });
        PanelNuevoHorario.add(jbLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 260, 40));

        jbGuardarHorario.setText("GUARDAR");
        jbGuardarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarHorarioActionPerformed(evt);
            }
        });
        PanelNuevoHorario.add(jbGuardarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 260, 40));

        LabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelNuevoHorario.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        getContentPane().add(PanelNuevoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
       jtextCodigoDocente.setText("");
        jtextHoraInicio.setText("");
         jtextHoraFin.setText("");
          jtextCantHora.setText("");
           jtextCurso.setText("");
            jtextCantDiaLab.setText("");
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbGuardarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarHorarioActionPerformed
       String HoraInicio= jtextHoraInicio.getText();
       String HoraFin=  jtextHoraFin.getText();
       String CantHora=  jtextCantHora.getText();
       String Curso=jtextCurso.getText();
       String CantDiaLab= jtextCantDiaLab.getText();
        String Dia="";    
          if  (jchkLun.isSelected()){
            Dia="LUN";
          }
          if  (jchkMar.isSelected()){
            Dia=Dia+",MAR";
          }
          if  (jchkMie.isSelected()){
            Dia=Dia+",MIE";
          }
          if  (jchkJue.isSelected()){
            Dia=Dia+",JUE";
          }
          if  (jchkVie.isSelected()){
            Dia=Dia+",VIE";
          }
          if  (jchkTodos.isSelected()){
             
            Dia="TODOS";
          }
           
        
      
      if (jbGuardarHorario.getText()=="Editar"){
            //Conexiones
              Horario horario=new Horario(0,HoraInicio,HoraFin,CantHora,Curso,CantDiaLab,Dia);
       cHorarioCrud p=new cHorarioCrud();
         p.actualizarHorario(conectar, horario);
        JOptionPane.showMessageDialog(null,"Se actualizo la persona correctamente"); 
       }else{
            cHorarioCrud h =new cHorarioCrud();
           IdPersonal = h.ObtenerIdPersonal(conectar,jtextCodigoDocente.getText());
           Horario horario =new Horario(IdPersonal,HoraInicio,HoraFin,CantHora,Curso,CantDiaLab,Dia);
           h.insertarHorario(conectar, horario);
        }
      Principal principal =new Principal();
       principal.setVisible(true);
       principal.ListarDatosHorario();
    }//GEN-LAST:event_jbGuardarHorarioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel Letrero1;
    private javax.swing.JPanel PanelBlanco;
    private javax.swing.JPanel PanelLetrero;
    private javax.swing.JPanel PanelNuevoHorario;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbGuardarHorario;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JCheckBox jchkJue;
    private javax.swing.JCheckBox jchkLun;
    private javax.swing.JCheckBox jchkMar;
    private javax.swing.JCheckBox jchkMie;
    private javax.swing.JCheckBox jchkTodos;
    private javax.swing.JCheckBox jchkVie;
    private javax.swing.JTextField jtextCantDiaLab;
    private javax.swing.JTextField jtextCantHora;
    private javax.swing.JTextField jtextCodigoDocente;
    private javax.swing.JTextField jtextCurso;
    private javax.swing.JTextField jtextHoraFin;
    private javax.swing.JTextField jtextHoraInicio;
    // End of variables declaration//GEN-END:variables
}
