/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
*Hecho por Alexis Robles
*31/11/2022
*Formulario para Logear al sistema
 */
package Forms;

import Clases.Boleta;
import Clases.ControladorExcel;
import Clases.EnviarCorreo;
import Clases.ExportarExcel;
import Clases.ModeloExcel;
import Clases.Planilla;
import Clases.cAsistenciaDetalleCrud;
import Clases.cBoletaCrud;
import Clases.cGenerarPdf2;
import Clases.cHorarioCrud;
import Clases.cPersonalCrud;
import Clases.cPlanillaCrud;
import Clases.cTarifaCrud;
import Clases.cTarifaDocCrud;
import Clases.cUsuarioCrud;
import Clases.conexion;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    //persona variables
      String IdPersonal="";
      String Nombre="";
      String Apellido="";
      String DNI="";
      String Hijos="";
      String Bancaria="";
      String Correo="";
      DefaultTableModel tabla;
    //horario variables
       String IdHorario="";
       String HoraInicio="";
       String Codigo="";
      String HoraFin="";
      String CantidadHora="";
      String Curso="";
      String CantidadDiasLab="";
      String Dias="";
      //tarifa variables
      String IdTarifa;
      String IdTarifaint;
      String CodigoTarifa;
      String Precio;
      String IdTarifaDoc;
      
    String NombresBoleta;
    String ApellidosBoleta;
    String SueldoxHoraBoleta;
    String HorasDictadasBoleta;
    String MontoDescporCategoriaBoleta;
    String MontoDescporSeguroBoleta;
    String MontoBonificacionBoleta;
    String SueldoNetoBoleta;
    String CuentaBancariaBoleta;
    String TipoBonificacionBoleta;
    String NivelBoleta;
    String SeguroSaludBoleta;
    String CodigoUsuarioBoleta;
    String MesBoleta;
    String AnioBoleta;
    String CategoriaBoleta;
    String DeduccionBoleta;
    String CorreoDestinoBoleta;
    public Principal() {
        initComponents();
         this.setLocationRelativeTo(null);
        //llamamos a las lista
        ListarDatos();
        ListarDatosHorario();
        ListarDatosTarifa();
        ListarDatosBoleta();
        ListarAsistenciaDetalle("","");
    }
           conexion con= new conexion();
       Connection conectar=con.establecerConexion();    
       void usuariologin(String Usuario) {
         
           jlblBienviendo.setText("BIENVENIDO: "+Usuario.toUpperCase());
        }
       //listar
    void ListarDatos(){
       cPersonalCrud p = new cPersonalCrud();
       jtPersonal.setModel(p.ListarPersonal(conectar));
    }
       void ListarDatosHorario(){
       cHorarioCrud p = new cHorarioCrud();
       jtHorario.setModel(p.ListarHorario(conectar));
    }
      void ListarDatosTarifa(){
       cTarifaCrud p = new cTarifaCrud();
       jtarifa.setModel(p.ListarTarifa(conectar));
    }
      void ListarDatosTarifaDoc(){
       cTarifaDocCrud td = new cTarifaDocCrud();
       jtarifadocente.setModel(td.ListarTarifaDoc(conectar,Integer.parseInt(IdTarifa)));
    }
      void ListarDatosBoleta(){
       cBoletaCrud bc = new cBoletaCrud();
       jtBoleta.setModel(bc.ListarBoleta(conectar));
    }
        void ListarAsistenciaDetalle(String Anio,String Mes){
       cAsistenciaDetalleCrud p = new cAsistenciaDetalleCrud();
       jAsistencia.setModel(p.ListarAsistenciaDetalle(conectar,Anio,Mes));
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        PanelBlanco = new javax.swing.JPanel();
        jlblBienviendo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelInicio = new javax.swing.JPanel();
        LabelFondo1 = new javax.swing.JLabel();
        PanelPersonal = new javax.swing.JPanel();
        PanelLetrero1 = new javax.swing.JPanel();
        Letrero1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPersonal = new javax.swing.JTable();
        jbCrear = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbActivar = new javax.swing.JButton();
        LabelFondo2 = new javax.swing.JLabel();
        PanelTurno = new javax.swing.JPanel();
        PanelLetrero2 = new javax.swing.JPanel();
        Letrero2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtHorario = new javax.swing.JTable();
        jbCrearHorario = new javax.swing.JButton();
        jbModificarHorario = new javax.swing.JButton();
        jbEliminarHorario = new javax.swing.JButton();
        LabelFondo3 = new javax.swing.JLabel();
        PanelAsistencia = new javax.swing.JPanel();
        PanelLetrero3 = new javax.swing.JPanel();
        btnRecargar = new javax.swing.JButton();
        cboAnioAsistencia = new javax.swing.JComboBox<>();
        cboMesAsistencia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBuscarTodo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jAsistencia = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        LabelFondo4 = new javax.swing.JLabel();
        Letrero3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jcAnio1 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        PanelTarifario = new javax.swing.JPanel();
        PanelLetrero4 = new javax.swing.JPanel();
        Letrero4 = new javax.swing.JLabel();
        btnRefrescarTarifario = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtarifadocente = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtarifa = new javax.swing.JTable();
        jbNuevoTarifaDoc = new javax.swing.JButton();
        jbTarifaDocEliminar = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jbNuevoTarifa = new javax.swing.JButton();
        jEliminarTarifa = new javax.swing.JButton();
        LabelFondo5 = new javax.swing.JLabel();
        PanelPlanilla = new javax.swing.JPanel();
        PanelLetrero5 = new javax.swing.JPanel();
        Letrero5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcAnio = new javax.swing.JComboBox<>();
        jcMes = new javax.swing.JComboBox<>();
        jtextCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbGenerar = new javax.swing.JButton();
        LabelFondo6 = new javax.swing.JLabel();
        PanelBoleta = new javax.swing.JPanel();
        PanelLetrero6 = new javax.swing.JPanel();
        Letrero6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtBoleta = new javax.swing.JTable();
        jbEnviarBoleta = new javax.swing.JButton();
        jbExportar = new javax.swing.JButton();
        EnviarTodos = new javax.swing.JButton();
        LabelFondo7 = new javax.swing.JLabel();

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido", "Asistencias", "Tardanzas", "Faltas", "Justificadas", "Total de Asistencias"
            }
        ));
        jTable4.setRowHeight(40);
        jScrollPane4.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido", "Asistencias", "Tardanzas", "Faltas", "Justificadas", "Total de Asistencias"
            }
        ));
        jTable5.setRowHeight(40);
        jScrollPane5.setViewportView(jTable5);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido", "Asistencias", "Tardanzas", "Faltas", "Justificadas", "Total de Asistencias"
            }
        ));
        jTable9.setRowHeight(40);
        jScrollPane9.setViewportView(jTable9);

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido", "Asistencias", "Tardanzas", "Faltas", "Justificadas", "Total de Asistencias"
            }
        ));
        jTable10.setRowHeight(40);
        jScrollPane10.setViewportView(jTable10);

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido", "Asistencias", "Tardanzas", "Faltas", "Justificadas", "Total de Asistencias"
            }
        ));
        jTable11.setRowHeight(40);
        jScrollPane11.setViewportView(jTable11);

        jButton10.setText("Cargar");

        jButton11.setText("Cargar");

        jButton18.setText("Nuevo");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        PanelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblBienviendo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PanelBlanco.add(jlblBienviendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 30));

        jButton3.setText("CERRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelBlanco.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 150, 30));

        getContentPane().add(PanelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 30));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelFondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelInicio.add(LabelFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 640));

        jTabbedPane1.addTab("Inicio", PanelInicio);

        PanelPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLetrero1.setBackground(new java.awt.Color(0, 2, 17));

        Letrero1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero1.setForeground(new java.awt.Color(255, 255, 255));
        Letrero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero1.setText("PERSONAL");

        javax.swing.GroupLayout PanelLetrero1Layout = new javax.swing.GroupLayout(PanelLetrero1);
        PanelLetrero1.setLayout(PanelLetrero1Layout);
        PanelLetrero1Layout.setHorizontalGroup(
            PanelLetrero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Letrero1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        PanelLetrero1Layout.setVerticalGroup(
            PanelLetrero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrero1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Letrero1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelPersonal.add(PanelLetrero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        jtPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Código", "Nombre", "Apellido", "Edad", "DNI", "Puesto", "N° de Hijos", "Categoría", "Deducción", "Nivel", "Estado"
            }
        ));
        jtPersonal.setRowHeight(40);
        jtPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPersonal);

        PanelPersonal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 780, -1));

        jbCrear.setText("Crear");
        jbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearActionPerformed(evt);
            }
        });
        PanelPersonal.add(jbCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 100, 40));

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });
        PanelPersonal.add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 100, 40));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        PanelPersonal.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 110, 40));

        jbActivar.setText("Activar");
        jbActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActivarActionPerformed(evt);
            }
        });
        PanelPersonal.add(jbActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 110, 40));

        LabelFondo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelPersonal.add(LabelFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jTabbedPane1.addTab("Personal", PanelPersonal);

        PanelTurno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLetrero2.setBackground(new java.awt.Color(0, 2, 17));

        Letrero2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero2.setForeground(new java.awt.Color(255, 255, 255));
        Letrero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero2.setText("HORARIO");

        javax.swing.GroupLayout PanelLetrero2Layout = new javax.swing.GroupLayout(PanelLetrero2);
        PanelLetrero2.setLayout(PanelLetrero2Layout);
        PanelLetrero2Layout.setHorizontalGroup(
            PanelLetrero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Letrero2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        PanelLetrero2Layout.setVerticalGroup(
            PanelLetrero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrero2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Letrero2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelTurno.add(PanelLetrero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        jtHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Código", "Nombre", "Apellido", "Hora Inicio ", "Hora Final ", "Horas Semanales", "Curso", "N° de días ", "Días Laborales"
            }
        ));
        jtHorario.setColumnSelectionAllowed(true);
        jtHorario.setRowHeight(40);
        jtHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHorarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtHorario);
        jtHorario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        PanelTurno.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 760, -1));

        jbCrearHorario.setText("Crear");
        jbCrearHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearHorarioActionPerformed(evt);
            }
        });
        PanelTurno.add(jbCrearHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 130, 40));

        jbModificarHorario.setText("Modificar");
        jbModificarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarHorarioActionPerformed(evt);
            }
        });
        PanelTurno.add(jbModificarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 120, 40));

        jbEliminarHorario.setText("Eliminar");
        jbEliminarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarHorarioActionPerformed(evt);
            }
        });
        PanelTurno.add(jbEliminarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 120, 40));

        LabelFondo3.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelTurno.add(LabelFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jTabbedPane1.addTab("Turno", PanelTurno);

        PanelAsistencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLetrero3.setBackground(new java.awt.Color(0, 2, 17));

        btnRecargar.setText("Buscar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        cboAnioAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025" }));

        cboMesAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mes:");

        btnBuscarTodo.setText("Buscar Todo");
        btnBuscarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLetrero3Layout = new javax.swing.GroupLayout(PanelLetrero3);
        PanelLetrero3.setLayout(PanelLetrero3Layout);
        PanelLetrero3Layout.setHorizontalGroup(
            PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrero3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboAnioAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMesAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        PanelLetrero3Layout.setVerticalGroup(
            PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrero3Layout.createSequentialGroup()
                .addGroup(PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLetrero3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(PanelLetrero3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRecargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAnioAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMesAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTodo))
                .addGap(13, 13, 13))
        );

        PanelAsistencia.add(PanelLetrero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        jAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido", "Asistencias", "Tardanzas", "Faltas", "Justificadas", "Total de Asistencias"
            }
        ));
        jAsistencia.setRowHeight(40);
        jScrollPane3.setViewportView(jAsistencia);

        PanelAsistencia.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 750, -1));

        jButton8.setText("Cargar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        PanelAsistencia.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 140, 40));

        LabelFondo4.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelAsistencia.add(LabelFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        Letrero3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero3.setForeground(new java.awt.Color(255, 255, 255));
        Letrero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero3.setText("ASISTENCIAS");
        PanelAsistencia.add(Letrero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 808, 46));

        jButton9.setText("Cargar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        PanelAsistencia.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 140, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 130, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 130, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 130, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 130, -1));

        jcAnio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "2022", "2023", "2024", "2025", "2026" }));
        PanelAsistencia.add(jcAnio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        PanelAsistencia.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        jTabbedPane1.addTab("Asistencia", PanelAsistencia);

        PanelTarifario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLetrero4.setBackground(new java.awt.Color(0, 2, 17));

        Letrero4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero4.setForeground(new java.awt.Color(255, 255, 255));
        Letrero4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero4.setText("Tarifario");

        btnRefrescarTarifario.setText("Refrescar");
        btnRefrescarTarifario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarTarifarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLetrero4Layout = new javax.swing.GroupLayout(PanelLetrero4);
        PanelLetrero4.setLayout(PanelLetrero4Layout);
        PanelLetrero4Layout.setHorizontalGroup(
            PanelLetrero4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLetrero4Layout.createSequentialGroup()
                .addComponent(Letrero4, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefrescarTarifario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        PanelLetrero4Layout.setVerticalGroup(
            PanelLetrero4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrero4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(PanelLetrero4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefrescarTarifario)
                    .addComponent(Letrero4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelTarifario.add(PanelLetrero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        jtarifadocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombres", "Apellidos", "Categoría", "Código de tarifa", "Tipo de afecto"
            }
        ));
        jtarifadocente.setRowHeight(40);
        jtarifadocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtarifadocenteMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jtarifadocente);

        PanelTarifario.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 490, 430));

        jtarifa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Código de precio", "Precio por hora"
            }
        ));
        jtarifa.setRowHeight(40);
        jtarifa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtarifaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jtarifa);

        PanelTarifario.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 430));

        jbNuevoTarifaDoc.setText("Nuevo");
        jbNuevoTarifaDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoTarifaDocActionPerformed(evt);
            }
        });
        PanelTarifario.add(jbNuevoTarifaDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 140, 40));

        jbTarifaDocEliminar.setText("Eliminar");
        jbTarifaDocEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTarifaDocEliminarActionPerformed(evt);
            }
        });
        PanelTarifario.add(jbTarifaDocEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 140, 40));

        jButton14.setText("Nuevo");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        PanelTarifario.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 140, 40));

        jbNuevoTarifa.setText("Nuevo");
        jbNuevoTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoTarifaActionPerformed(evt);
            }
        });
        PanelTarifario.add(jbNuevoTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 100, 40));

        jEliminarTarifa.setText("Eliminar");
        jEliminarTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarTarifaActionPerformed(evt);
            }
        });
        PanelTarifario.add(jEliminarTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 100, 40));

        LabelFondo5.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelTarifario.add(LabelFondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jTabbedPane1.addTab("Tarifario", PanelTarifario);

        PanelPlanilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLetrero5.setBackground(new java.awt.Color(0, 2, 17));

        Letrero5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero5.setForeground(new java.awt.Color(255, 255, 255));
        Letrero5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero5.setText("PLANILLA");

        javax.swing.GroupLayout PanelLetrero5Layout = new javax.swing.GroupLayout(PanelLetrero5);
        PanelLetrero5.setLayout(PanelLetrero5Layout);
        PanelLetrero5Layout.setHorizontalGroup(
            PanelLetrero5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Letrero5, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        PanelLetrero5Layout.setVerticalGroup(
            PanelLetrero5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrero5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Letrero5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelPlanilla.add(PanelLetrero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Codigo Personal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Año");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mes");

        jcAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "2022", "2023", "2024", "2025", "2026" }));

        jcMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\LogoPrincipalColegio.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(101, 101, 101)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jcMes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcAnio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        PanelPlanilla.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, 430));

        jbGenerar.setText("GENERAR");
        jbGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarActionPerformed(evt);
            }
        });
        PanelPlanilla.add(jbGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 260, 40));

        LabelFondo6.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelPlanilla.add(LabelFondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jTabbedPane1.addTab("Planilla", PanelPlanilla);

        PanelBoleta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLetrero6.setBackground(new java.awt.Color(0, 2, 17));

        Letrero6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero6.setForeground(new java.awt.Color(255, 255, 255));
        Letrero6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero6.setText("BOLETA DE PAGO");

        javax.swing.GroupLayout PanelLetrero6Layout = new javax.swing.GroupLayout(PanelLetrero6);
        PanelLetrero6.setLayout(PanelLetrero6Layout);
        PanelLetrero6Layout.setHorizontalGroup(
            PanelLetrero6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLetrero6Layout.createSequentialGroup()
                .addComponent(Letrero6, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addGap(152, 152, 152))
        );
        PanelLetrero6Layout.setVerticalGroup(
            PanelLetrero6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetrero6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Letrero6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelBoleta.add(PanelLetrero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        jtBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombres", "Apellidos", "Año - Mes", "Estado de planilla"
            }
        ));
        jtBoleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtBoletaMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jtBoleta);

        PanelBoleta.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 740, -1));

        jbEnviarBoleta.setText("Enviar Boleta");
        jbEnviarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarBoletaActionPerformed(evt);
            }
        });
        PanelBoleta.add(jbEnviarBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 140, 40));

        jbExportar.setText("Exportar");
        jbExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExportarActionPerformed(evt);
            }
        });
        PanelBoleta.add(jbExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 140, 40));

        EnviarTodos.setText("Enviar Todos");
        EnviarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarTodosActionPerformed(evt);
            }
        });
        PanelBoleta.add(EnviarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 116, 40));

        LabelFondo7.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N
        PanelBoleta.add(LabelFondo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jTabbedPane1.addTab("Boleta", PanelBoleta);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCrearHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearHorarioActionPerformed
       //Poner Formulario Visible
        NuevoHorario horario =new NuevoHorario();
        horario.setVisible(true);
    }//GEN-LAST:event_jbCrearHorarioActionPerformed

    private void jbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearActionPerformed
       //llamar a formulario Nuevo Personal y pornerlo como visible
        NuevoPersonal personal =new NuevoPersonal();
        personal.Tipo("I");
       // FrmMenu menu =new FrmMenu();
        personal.setVisible(true);
      //  ListarHoraioario();
    }//GEN-LAST:event_jbCrearActionPerformed

    private void jbNuevoTarifaDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoTarifaDocActionPerformed
         //llamar a formulario NuevaTarifaDocente y pornerlo como visible
        NuevaTarifaDocente tarifadoc =new NuevaTarifaDocente();
        JOptionPane.showMessageDialog(null,IdTarifaint+""+IdTarifa); 
        tarifadoc.ListarTarifaDetalle(IdTarifaint, CodigoTarifa);
        tarifadoc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jbNuevoTarifaDocActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jbNuevoTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoTarifaActionPerformed
        //llamar a formulario NuevaTarifa y pornerlo como visible
        NuevaTarifa tarifa =new NuevaTarifa();
        tarifa.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jbNuevoTarifaActionPerformed

    private void jbGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarActionPerformed
        //Generar Planilla, seteo mes, Anio, CodigoPersonal
        String Mes =String.valueOf(jcMes.getSelectedItem());
        String Anio =String.valueOf(jcAnio.getSelectedItem());
        String CodigoPersonal=jtextCodigo.getText();
        Planilla p =new Planilla(CodigoPersonal,Mes,Anio);
        cPlanillaCrud pc = new cPlanillaCrud();
         pc.cGenerarPlanilla(conectar, p);
          ListarDatosBoleta();
    }//GEN-LAST:event_jbGenerarActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jbEnviarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarBoletaActionPerformed
       //Enviar Boleta de pago
        Boleta b = new Boleta(NombresBoleta,ApellidosBoleta,SueldoxHoraBoleta,HorasDictadasBoleta,MontoDescporCategoriaBoleta,MontoDescporSeguroBoleta,MontoBonificacionBoleta,SueldoNetoBoleta,CuentaBancariaBoleta,TipoBonificacionBoleta,NivelBoleta,SeguroSaludBoleta,CodigoUsuarioBoleta,MesBoleta,AnioBoleta,CategoriaBoleta,DeduccionBoleta,CorreoDestinoBoleta);
        cGenerarPdf2 c = new cGenerarPdf2();
          JOptionPane.showMessageDialog(null, 
                "Se creo el archivo Boleta.pdf en la carpeta del proyecto");
         c.generar(b);
         EnviarCorreo e = new EnviarCorreo();
          try {
              e.main(CorreoDestinoBoleta);
                JOptionPane.showMessageDialog(null,"Correo enviado con éxito"); 
              // TODO add your handling code here:
          } catch (MessagingException ex) {
              Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jbEnviarBoletaActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        NuevoPersonal personal =new NuevoPersonal();
       // FrmMenu menu =new FrmMenu();
        personal.setVisible(true);
        personal.ListarData(Nombre, Apellido, DNI, Hijos, Bancaria, Correo,IdPersonal);
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
         cPersonalCrud eliminarpersonal = new cPersonalCrud(); 
        eliminarpersonal.eliminarPersonal(conectar, IdPersonal);
        ListarDatos();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActivarActionPerformed
        cPersonalCrud actualizar = new cPersonalCrud(); 
        
        actualizar.UpdateActivo(conectar, IdPersonal);
        ListarDatos();
    }//GEN-LAST:event_jbActivarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

            
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jtPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPersonalMouseClicked
       //hola
       int seleccionar=jtPersonal.rowAtPoint(evt.getPoint());
     IdPersonal=(String.valueOf(jtPersonal.getValueAt(seleccionar, 0)));
        Nombre=(String.valueOf(jtPersonal.getValueAt(seleccionar, 1)));
        Apellido=(String.valueOf(jtPersonal.getValueAt(seleccionar, 2)));
        DNI=(String.valueOf(jtPersonal.getValueAt(seleccionar, 4)));
        Hijos=(String.valueOf(jtPersonal.getValueAt(seleccionar, 5)));
        Bancaria=(String.valueOf(jtPersonal.getValueAt(seleccionar, 6)));
        Correo=(String.valueOf(jtPersonal.getValueAt(seleccionar, 7)));
                   
    }//GEN-LAST:event_jtPersonalMouseClicked

    private void jbEliminarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarHorarioActionPerformed
         cHorarioCrud eliminarhorario = new cHorarioCrud(); 
        
        eliminarhorario.eliminarHorario(conectar, IdHorario);
        ListarDatosHorario();
    }//GEN-LAST:event_jbEliminarHorarioActionPerformed

    private void jtHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHorarioMouseClicked
       int seleccionar=jtHorario.rowAtPoint(evt.getPoint());
       IdHorario=(String.valueOf(jtHorario.getValueAt(seleccionar, 0)));
       Codigo=(String.valueOf(jtHorario.getValueAt(seleccionar, 2)));
       HoraInicio=(String.valueOf(jtHorario.getValueAt(seleccionar, 5)));
       HoraFin=(String.valueOf(jtHorario.getValueAt(seleccionar, 6)));
       CantidadHora=(String.valueOf(jtHorario.getValueAt(seleccionar, 7)));
       Curso=(String.valueOf(jtHorario.getValueAt(seleccionar, 8)));
       CantidadDiasLab=(String.valueOf(jtHorario.getValueAt(seleccionar, 9)));
       Dias=(String.valueOf(jtHorario.getValueAt(seleccionar, 10)));
 
       ListarDatosHorario();
    }//GEN-LAST:event_jtHorarioMouseClicked

    private void jbModificarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarHorarioActionPerformed
          NuevoHorario horario =new NuevoHorario();
       // FrmMenu menu =new FrmMenu();
        horario.setVisible(true);
        horario.ListarDataHorario(IdHorario,Codigo,HoraInicio,HoraFin,
                        CantidadHora,Curso,CantidadDiasLab,Dias);
    }//GEN-LAST:event_jbModificarHorarioActionPerformed

    private void jEliminarTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarTarifaActionPerformed
        cTarifaCrud eliminarTarifa = new cTarifaCrud(); 
        eliminarTarifa.eliminarTarifa(conectar, IdTarifa);
        ListarDatosTarifa();// TODO add your handling code here:
    }//GEN-LAST:event_jEliminarTarifaActionPerformed

    private void jtarifaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtarifaMouseClicked
        // TODO add your handling code here:
       int seleccionar=jtarifa.rowAtPoint(evt.getPoint());
       IdTarifa=(String.valueOf(jtarifa.getValueAt(seleccionar, 0)));
       CodigoTarifa=(String.valueOf(jtarifa.getValueAt(seleccionar, 1)));
       Precio=(String.valueOf(jtarifa.getValueAt(seleccionar, 2)));    
       IdTarifaint=(String.valueOf(jtarifa.getValueAt(seleccionar, 0)));  
       ListarDatosTarifaDoc();
    }//GEN-LAST:event_jtarifaMouseClicked

    private void jbTarifaDocEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTarifaDocEliminarActionPerformed
        cTarifaDocCrud eliminarTarifadoc = new cTarifaDocCrud(); 
        eliminarTarifadoc.eliminarTarifaDoc(conectar, IdTarifaDoc);
        ListarDatosTarifaDoc();// TODO add your handling code here:
    }//GEN-LAST:event_jbTarifaDocEliminarActionPerformed

    private void jtarifadocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtarifadocenteMouseClicked
         int seleccionar=jtarifadocente.rowAtPoint(evt.getPoint());
       IdTarifaDoc=(String.valueOf(jtarifadocente.getValueAt(seleccionar, 0)));

    }//GEN-LAST:event_jtarifadocenteMouseClicked

    private void jtBoletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBoletaMouseClicked
        int seleccionar=jtBoleta.rowAtPoint(evt.getPoint());
     NombresBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 0)));
     ApellidosBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 1)));
     SueldoxHoraBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 2)));
     HorasDictadasBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 3)));
     MontoDescporCategoriaBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 4)));
     MontoDescporSeguroBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 5)));
     MontoBonificacionBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 6)));
     SueldoNetoBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 7)));
     CuentaBancariaBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 8)));
     TipoBonificacionBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 9)));
     NivelBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 10)));
     SeguroSaludBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 11)));
     CodigoUsuarioBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 12)));
     MesBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 13)));
     AnioBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 14)));
     CategoriaBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 15)));
     DeduccionBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 16)));
     CorreoDestinoBoleta=(String.valueOf(jtBoleta.getValueAt(seleccionar, 17)));  
       ListarDatosBoleta();
    }//GEN-LAST:event_jtBoletaMouseClicked

    private void jbExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExportarActionPerformed
    ExportarExcel e =new ExportarExcel();
          try {
              e.exportarExcel(jtBoleta);// TODO add your handling code here:
          } catch (IOException ex) {
              Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jbExportarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ModeloExcel ModeloEX=new ModeloExcel();
        VistaExcel VistaEX=new VistaExcel();
        ControladorExcel ControlExcel=new ControladorExcel(VistaEX, ModeloEX);  
        ListarAsistenciaDetalle("","");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
// Sirve para actualizar el boton de asistencia
    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        String Anio =String.valueOf(cboAnioAsistencia.getSelectedItem());
        String  Mes=String.valueOf(cboMesAsistencia.getSelectedItem());
        ListarAsistenciaDetalle(Anio,Mes);
    }//GEN-LAST:event_btnRecargarActionPerformed
// Envío de boleta
    private void EnviarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarTodosActionPerformed
             if(jtBoleta.getRowCount()>0){
          for (int i=0;i<jtBoleta.getRowCount();i++){
            String NombresBoleta=    String.valueOf(jtBoleta.getValueAt(i,0));
            String ApellidosBoleta=    String.valueOf( jtBoleta.getValueAt(i,1));
            String SueldoxHoraBoleta=    String.valueOf(jtBoleta.getValueAt(i,2));
            String HorasDictadasBoleta=    String.valueOf(jtBoleta.getValueAt(i,3));
            String MontoDescporCategoriaBoleta=    String.valueOf(jtBoleta.getValueAt(i,4));
            String MontoDescporSeguroBoleta=    String.valueOf(jtBoleta.getValueAt(i,5));
            String MontoBonificacionBoleta=    String.valueOf(jtBoleta.getValueAt(i,6));
            String SueldoNetoBoleta=    String.valueOf(jtBoleta.getValueAt(i,7));
            String CuentaBancariaBoleta=    String.valueOf(jtBoleta.getValueAt(i,8));
            String TipoBonificacionBoleta=    String.valueOf(jtBoleta.getValueAt(i,9));
            String NivelBoleta=    String.valueOf(jtBoleta.getValueAt(i,10));
            String SeguroSaludBoleta=    String.valueOf(jtBoleta.getValueAt(i,11));
             String CodigoUsuarioBoleta=    String.valueOf(jtBoleta.getValueAt(i,12));
            String MesBoleta=    String.valueOf(jtBoleta.getValueAt(i,13));
            String AnioBoleta=    String.valueOf(jtBoleta.getValueAt(i,14));
            String CategoriaBoleta=    String.valueOf(jtBoleta.getValueAt(i,15));
            String DeduccionBoleta=    String.valueOf(jtBoleta.getValueAt(i,16));
            String CorreoDestinoBoleta=    String.valueOf(jtBoleta.getValueAt(i,17));
//JOptionPane.showMessageDialog(this, codigo+Nombre+Apellido+Asistencia+Tardanza+Falta+Justificada+TotalAsistencia+HoraporAsistencia+TotalHora+Mes+Anio);
                if (CodigoUsuarioBoleta!="null"){
                Boleta b = new Boleta(NombresBoleta,ApellidosBoleta,SueldoxHoraBoleta,HorasDictadasBoleta,
                        MontoDescporCategoriaBoleta,MontoDescporSeguroBoleta,MontoBonificacionBoleta,
                        SueldoNetoBoleta,CuentaBancariaBoleta,TipoBonificacionBoleta,NivelBoleta,SeguroSaludBoleta,
                        CodigoUsuarioBoleta,MesBoleta,AnioBoleta,CategoriaBoleta,DeduccionBoleta,CorreoDestinoBoleta);
                    cGenerarPdf2 c = new cGenerarPdf2();
                     c.generar(b);
                     EnviarCorreo e = new EnviarCorreo();
                      try {
                          e.main(CorreoDestinoBoleta);
                          // TODO add your handling code here:
                      } catch (MessagingException ex) {
                          Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                      } 
                
       }
      
          }
           JOptionPane.showMessageDialog(null,"Correos enviados con éxito");
      }else{
      JOptionPane.showMessageDialog(this, "La tabla se encuentra vacia");
      }
    }//GEN-LAST:event_EnviarTodosActionPerformed

    private void btnRefrescarTarifarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarTarifarioActionPerformed
        // TODO add your handling code here:
        ListarDatosTarifa();
    }//GEN-LAST:event_btnRefrescarTarifarioActionPerformed

    private void btnBuscarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTodoActionPerformed
        // TODO add your handling code here:
        ListarAsistenciaDetalle("","");
    }//GEN-LAST:event_btnBuscarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarTodos;
    private javax.swing.JLabel LabelFondo1;
    private javax.swing.JLabel LabelFondo2;
    private javax.swing.JLabel LabelFondo3;
    private javax.swing.JLabel LabelFondo4;
    private javax.swing.JLabel LabelFondo5;
    private javax.swing.JLabel LabelFondo6;
    private javax.swing.JLabel LabelFondo7;
    private javax.swing.JLabel Letrero1;
    private javax.swing.JLabel Letrero2;
    private javax.swing.JLabel Letrero3;
    private javax.swing.JLabel Letrero4;
    private javax.swing.JLabel Letrero5;
    private javax.swing.JLabel Letrero6;
    private javax.swing.JPanel PanelAsistencia;
    private javax.swing.JPanel PanelBlanco;
    private javax.swing.JPanel PanelBoleta;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelLetrero1;
    private javax.swing.JPanel PanelLetrero2;
    private javax.swing.JPanel PanelLetrero3;
    private javax.swing.JPanel PanelLetrero4;
    private javax.swing.JPanel PanelLetrero5;
    private javax.swing.JPanel PanelLetrero6;
    private javax.swing.JPanel PanelPersonal;
    private javax.swing.JPanel PanelPlanilla;
    private javax.swing.JPanel PanelTarifario;
    private javax.swing.JPanel PanelTurno;
    private javax.swing.JButton btnBuscarTodo;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnRefrescarTarifario;
    private javax.swing.JComboBox<String> cboAnioAsistencia;
    private javax.swing.JComboBox<String> cboMesAsistencia;
    private javax.swing.JTable jAsistencia;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JButton jEliminarTarifa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable9;
    private javax.swing.JButton jbActivar;
    private javax.swing.JButton jbCrear;
    private javax.swing.JButton jbCrearHorario;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbEliminarHorario;
    private javax.swing.JButton jbEnviarBoleta;
    private javax.swing.JButton jbExportar;
    private javax.swing.JButton jbGenerar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbModificarHorario;
    private javax.swing.JButton jbNuevoTarifa;
    private javax.swing.JButton jbNuevoTarifaDoc;
    private javax.swing.JButton jbTarifaDocEliminar;
    private javax.swing.JComboBox<String> jcAnio;
    private javax.swing.JComboBox<String> jcAnio1;
    private javax.swing.JComboBox<String> jcMes;
    private javax.swing.JLabel jlblBienviendo;
    private javax.swing.JTable jtBoleta;
    private javax.swing.JTable jtHorario;
    private javax.swing.JTable jtPersonal;
    private javax.swing.JTable jtarifa;
    private javax.swing.JTable jtarifadocente;
    private javax.swing.JTextField jtextCodigo;
    // End of variables declaration//GEN-END:variables
}
