/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.AsistenciaDetalle;
import Clases.cAsistenciaDetalleCrud;
import Clases.conexion;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author JeanCarlos
 */
public class VistaExcel extends javax.swing.JFrame {

    /**
     * Creates new form VistaExcel
     */
    public VistaExcel() {
        initComponents();
         this.setLocationRelativeTo(null);
    }
      conexion con= new conexion();
       Connection conectar=con.establecerConexion();    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DatosExcel = new javax.swing.JTable();
        PanelLetrero3 = new javax.swing.JPanel();
        Letrero3 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        LabelFondo4 = new javax.swing.JLabel();
        btnCargarSql = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        DatosExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DatosExcel);

        PanelLetrero3.setBackground(new java.awt.Color(0, 2, 17));

        Letrero3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        Letrero3.setForeground(new java.awt.Color(255, 255, 255));
        Letrero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Letrero3.setText("ASISTENCIAS");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLetrero3Layout = new javax.swing.GroupLayout(PanelLetrero3);
        PanelLetrero3.setLayout(PanelLetrero3Layout);
        PanelLetrero3Layout.setHorizontalGroup(
            PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLetrero3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(Letrero3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(70, 70, 70))
        );
        PanelLetrero3Layout.setVerticalGroup(
            PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLetrero3Layout.createSequentialGroup()
                .addGroup(PanelLetrero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLetrero3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Letrero3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLetrero3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnCerrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LabelFondo4.setIcon(new javax.swing.ImageIcon("C:\\Users\\apsenior\\Downloads\\ProyectoCasiCasiFinal\\SendMailBasic_Maven-main\\src\\main\\java\\Imagenes\\ColegioCompleto.jpg")); // NOI18N

        btnCargarSql.setText("Cargar");
        btnCargarSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarSqlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnCargarSql, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelLetrero3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(LabelFondo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelLetrero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarSql, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(121, Short.MAX_VALUE)
                    .addComponent(LabelFondo4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnCargarSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarSqlActionPerformed
      if(DatosExcel.getRowCount()>0){
          for (int i=0;i<DatosExcel.getRowCount();i++){
            String codigo=    String.valueOf(DatosExcel.getValueAt(i,0));
            String Nombre=    String.valueOf( DatosExcel.getValueAt(i,1));
            String Apellido=    String.valueOf(DatosExcel.getValueAt(i,2));
            String Asistencia=    String.valueOf(DatosExcel.getValueAt(i,3));
            String Tardanza=    String.valueOf(DatosExcel.getValueAt(i,4));
            String Falta=    String.valueOf(DatosExcel.getValueAt(i,5));
            String Justificada=    String.valueOf(DatosExcel.getValueAt(i,6));
            String TotalAsistencia=    String.valueOf(DatosExcel.getValueAt(i,7));
            String HoraporAsistencia=    String.valueOf(DatosExcel.getValueAt(i,8));
            String TotalHora=    String.valueOf(DatosExcel.getValueAt(i,9));
            String Mes=    String.valueOf(DatosExcel.getValueAt(i,10));
            String Anio=    String.valueOf(DatosExcel.getValueAt(i,11));
//JOptionPane.showMessageDialog(this, codigo+Nombre+Apellido+Asistencia+Tardanza+Falta+Justificada+TotalAsistencia+HoraporAsistencia+TotalHora+Mes+Anio);
                if (codigo!="null"){
                 AsistenciaDetalle ad =new AsistenciaDetalle(codigo,Nombre,Apellido,Asistencia,Tardanza,Falta,Justificada,TotalAsistencia,HoraporAsistencia,TotalHora,Mes,Anio);
                              cAsistenciaDetalleCrud cadc=new cAsistenciaDetalleCrud();
                              cadc.insertarAsistenciaDet(conectar, ad);
                }
               
          }
           JOptionPane.showMessageDialog(this, "Se procedio a cargar la data");
      }else{
      JOptionPane.showMessageDialog(this, "La tabla se encuentra vacia");
      }
      
         
    }//GEN-LAST:event_btnCargarSqlActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaExcel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable DatosExcel;
    private javax.swing.JLabel LabelFondo4;
    private javax.swing.JLabel Letrero3;
    private javax.swing.JPanel PanelLetrero3;
    private javax.swing.JButton btnCargarSql;
    private javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnImportar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
